Vagrant.configure("2") do |config|
    # Setting vm box 
    config.vm.box = "ubuntu/focal64"

    # Setting vm hostname
    config.vm.hostname = "frontend"

    # Create a forwarded port
    config.vm.network "forwarded_port", guest: 30800, host: 30800
  
    # Create a private network, which allows host-only access to the machine
    config.vm.network "private_network", ip: "192.168.61.2",
      virtualbox__intnet: true

    # Using bash script to setting environment
    config.vm.provision "shell", inline: "/vagrant/setup.sh", privileged: false
  end